name: 'Setup Subversion'
description: 'Set up Apache Subversion (svn) command line tool'
branding:
  icon: 'download'
  color: 'blue'

inputs:
  svn-version:
    description: 'Version of Subversion to install (default: latest available from package manager)'
    required: false
    default: ''

outputs:
  svn-version:
    description: 'The installed version of Subversion'
    value: ${{ steps.svn-info.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Install Subversion on Ubuntu/Debian
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion
        
    - name: Install Subversion on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install subversion
        
    - name: Install Subversion on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install -y svn
        
    - name: Add Subversion to PATH on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # Chocolatey typically installs to C:\Program Files\Subversion\bin
        $svnPath = "C:\Program Files\Subversion\bin"
        if (Test-Path $svnPath) {
          echo "$svnPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          # Also add to current session PATH
          $env:Path = "$svnPath;$env:Path"
        }
        # Refresh environment to pick up Chocolatey changes
        refreshenv
        
    - name: Verify installation and get version
      id: svn-info
      shell: bash
      run: |
        svn --version --quiet
        echo "version=$(svn --version --quiet)" >> $GITHUB_OUTPUT
        
    - name: Verify svnadmin is available
      shell: bash
      run: |
        svnadmin --version
        
    - name: Display Subversion info
      shell: bash
      run: |
        echo "Subversion installed successfully!"
        echo "Commands available: svn, svnadmin, svnlook, svnsync, svnrdump, svnserve, svnversion, svnmucc"
        echo ""
        svn --version
        echo ""
        echo "svn location: $(which svn || where svn)"
        echo "svnadmin location: $(which svnadmin || where svnadmin)"